# Numpy - Array

* Mucho más rápido que la lista

In [1]:
import numpy as np
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
arreglo = np.array(lista)
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arreglo)

numpy.ndarray

## Matriz

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* Indexado - Elementos específicos

In [9]:
arreglo[0]

1

In [10]:
arreglo[1]

2

In [11]:
arreglo[0] + arreglo[5]

7

* Indexado Matrices - Elementos Específicos

In [14]:
matriz[0]

array([1, 2, 3])

In [16]:
matriz[0][2]

3

* Slicing

In [20]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#No se toma en cuenta el último indice
arreglo[0:3]

array([1, 2, 3])

In [19]:
arreglo[1:6]

array([2, 3, 4, 5, 6])

In [22]:
#Desde
arreglo[2:]
arreglo[:3]

array([1, 2, 3])

In [23]:
#Dando Saltos
arreglo[::2]

array([1, 3, 5, 7, 9])

In [24]:
#Modo de invertirlo
arreglo[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [28]:
#Tomar los elementos desde el último
arreglo[-3:]

array([7, 8, 9])

In [29]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# Se lee: Trae todo desde la fila de indice 1, y en columnas desde el indice 0 hasta el indice 2 sin contarlo.
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])