# Condiciones

In [1]:
import numpy as np

In [3]:
arreglo = np.linspace(1,10,10,dtype="int8")
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
#Esta es una condicion
arreglo > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
condicion = arreglo > 5

In [7]:
arreglo[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

* condicion compuesta

In [11]:
condicion = (arreglo > 5) & (arreglo < 8)
arreglo[condicion]

array([6, 7], dtype=int8)

In [12]:
arreglo[condicion] = 0

In [13]:
arreglo

array([ 1,  2,  3,  4,  5,  0,  0,  8,  9, 10], dtype=int8)

In [14]:
arreglo[arreglo==0]

array([0, 0], dtype=int8)

# Conclusión:
* Se entiende muchísimo mejor las funciones que Pandas obtiene por defecto y su emparejamiento con numpy

* Nunca olvidar np.where