# Copy

In [10]:
import numpy as np

In [11]:
arreglo = np.arange(0,11)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Slicing
trozo = arreglo[0:6]

In [13]:
trozo

array([0, 1, 2, 3, 4, 5])

In [14]:
#Cambiamos todos los elementos de Trozo po 0
trozo[:] = 0
trozo

array([0, 0, 0, 0, 0, 0])

* Pero sucede un problema!!!
* Hemos modificado nuestro arreglo base!!

In [15]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

¿Cómo Arreglarlo?

* Recuerda que se sigue haciendo referencia al objeto padre

In [16]:
arreglo_copia = arreglo.copy()

In [17]:
arreglo_copia[:] = 100
arreglo_copia

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

* Podemos ver que nuestro arreglo original nunca fue modificado

## Conclusión:
* Siempre que trabajemos con un trozo de un arreglo, matriz o tensor, es primordial crear una copia de ese objeto
* Es una excelente práctica, no te arriesgues!!