# Creación de Arrays - Métodos

In [1]:
import numpy as np

In [3]:
#Ejemplo
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#Un array de números desde el 0 al (10-1)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Un array de números salteados
np.arange(0,20,2) #El último dos → saltos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#Crear Arreglos con 0
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
#Crear Arreglos con 1
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#Crear una sencuencia de números
np.linspace(0,10,3) #Obtengo datos del 0 al 10, 3 de estos exactamente. 

array([ 0.,  5., 10.])

In [15]:
#Crear la funcion "ojo", diagonal principal con 1
#Matriz de elemento Neutro
np.eye(4) #Matriz indentidad de dimensión 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Valores Aleatorios

In [28]:
#Numero aleatorio entre 0 y 1
np.random.rand()

0.9283877756213811

In [29]:
#Obtienes 5 elementos aleatorios entre 0 y 1
np.random.rand(5)

array([0.38754202, 0.53171806, 0.81512151, 0.85449813, 0.58434237])

In [30]:
#Obtienes una matriz de elementos 2 x 3 entre 0 y 1
np.random.rand(2,3)

array([[0.09602711, 0.4874416 , 0.6566886 ],
       [0.51719913, 0.82932848, 0.17082909]])

* Aleatorios Enteros

In [40]:
#Obtener un entero aleatorio entre 1 y 15
np.random.randint(1,15)

13

In [41]:
#Obtener un arreglo de números enteros aleatorios
np.random.randint(1,20,(5,5)) #Arreglo de 5x5 aleatorio. 

array([[ 5, 19,  8,  8, 11],
       [19, 19,  1,  7, 12],
       [ 8,  7, 13, 19, 13],
       [18,  6, 11,  1, 19],
       [15, 15,  7, 17, 17]])