# Dimensiones

In [4]:
import numpy as np
scalar = np.array(42)
print(scalar)
scalar.shape

42


()

* Vectores

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

* Matriz

In [6]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz.ndim

2

# Agregar o Eliminar Dimensiones

In [20]:
#Definir dimensionalidad
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [19]:
#Subir una dimensión a la indicada. 
expand = np.expand_dims(np.array([1,2,3]),axis=0) #axis depende de los ejes
expand

array([[1, 2, 3]])

In [21]:
#Eliminar Dimensiones
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) #np.squeeze reduce tu arreglo a un número de dimensiones adecuado. 
vector_2

[[[[[[[[[[1 2 3]]]]]]]]]] 10


array([1, 2, 3])