# Funciones Principales

In [6]:
import numpy as np

In [7]:
arreglo = np.random.randint(1,20,10)

In [8]:
matriz = arreglo.reshape(2,5)

* Nos otorga el número más grande del arreglo

In [9]:
arreglo.max()

18

In [11]:
matriz

array([[ 1, 11,  5, 14, 13],
       [18, 10,  4,  8,  6]])

* 0: Por columna
* 1: Por fila

In [15]:
#Número Máximos por columna
matriz.max(0)

array([18, 11,  5, 14, 13])

In [16]:
#Números máximos por fila
matriz.max(1)

array([14, 18])

In [18]:
arreglo

array([ 1, 11,  5, 14, 13, 18, 10,  4,  8,  6])

In [17]:
#Devuelve el indice del elemento mayor. 
arreglo.argmax()

5

* Lo mismo Aplica con "MIN" Obviamente.

In [20]:
arreglo

array([ 1, 11,  5, 14, 13, 18, 10,  4,  8,  6])

In [19]:
#Limite superior - Limite inferior
arreglo.ptp()

17

In [24]:
arreglo.sort()
arreglo

array([ 1,  4,  5,  6,  8, 10, 11, 13, 14, 18])

In [22]:
# Cual es el valor que contiene el 50% de los datos
np.percentile(arreglo,50) #Esta es la mediana

9.0

In [25]:
#Mediana es igual al percentil 50
np.median(arreglo)

9.0

In [26]:
#La Mediana por columa de una matriz
np.median(matriz,0)

array([ 5.5,  7.5,  9. , 10. , 13. ])

In [27]:
#La Mediana por fila de una matriz:
np.median(matriz,1)

array([ 5., 13.])

In [32]:
#Desviación Estándar
np.std(arreglo)

4.919349550499537

In [29]:
#Variacion
np.var(arreglo)

24.2

In [33]:
#Media
np.mean(arreglo)

9.0

In [43]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

# Unir Array A y array B

* Concatenaremos por fila

In [44]:
a.ndim

2

In [45]:
b.ndim

1

In [48]:
#Expandemo b a otra dimension para igualar a la de A
b = np.expand_dims(b,axis=0)

In [49]:
#Ya operado procedemos a concatenar
np.concatenate((a,b),axis=0) #concatenamos por filas

array([[1, 2],
       [3, 4],
       [5, 6]])

* Concatenamos por Columna

In [52]:
a

array([[1, 2],
       [3, 4]])

In [54]:
b.T

array([[5],
       [6]])

In [51]:
np.concatenate((a,b.T),axis=1) #concatenamos por columa axis = 1

array([[1, 2, 5],
       [3, 4, 6]])