# Operaciones

In [1]:
import numpy as np

* Las Listas no operan correctamente 

In [3]:
lista = [1,2]
lista

[1, 2]

In [4]:
lista * 2

[1, 2, 1, 2]

* Los Arreglos si operan datos correctamente

In [6]:
arreglo = np.arange(0,10)
arreglo2 = arreglo.copy()

In [11]:
#Cada elemento fue elevado al cuadrado
arreglo**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arreglo+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#Ten cuidado!!
1/arreglo

C:\Users\User\AppData\Local\Temp\ipykernel_1344\3790602442.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arreglo


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
#Puedo sumar arreglos
arreglo + arreglo2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arreglo / arreglo2

C:\Users\User\AppData\Local\Temp\ipykernel_1344\3448167025.py:1: RuntimeWarning: invalid value encountered in true_divide
  arreglo / arreglo2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
matriz = arreglo.reshape(2,5)
matriz2 = matriz.copy()

In [19]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Multiplicar Matrices

In [21]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [20]:
#Multiplicacion de matriz convencional
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

* Forma resumida de multiplicación de matrices

In [24]:
#Esta forma es estupenda
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# Conclusión
* Aplicas la transpuesta porque recuerda mxn y nxp entonces se pueden multiplicar