# Shape y Reshape

In [2]:
import numpy as np
arreglo = np.random.randint(1,10,(3,2)) #(3,2) es su shape

In [3]:
#Nos revela la forma del arreglo
arreglo.shape

(3, 2)

* Arreglo Original

In [9]:
arreglo

array([[5, 4],
       [3, 2],
       [8, 3]])

In [7]:
#Redimensionar. el producto de filas y columnas no debe variar
arreglo.reshape(1,6)

array([[5, 4, 3, 2, 8, 3]])

In [8]:
np.reshape(arreglo,(2,3))

array([[5, 4, 3],
       [2, 8, 3]])

In [14]:
#Forma por defecto de redimensión
np.reshape(arreglo,(2,3),"C")

array([[5, 4, 3],
       [2, 8, 3]])

In [13]:
#Forma alternativa de redimensión
np.reshape(arreglo,(2,3),"F")

array([[5, 8, 2],
       [3, 4, 3]])

In [15]:
#Realiza la opción más optimizada. 
np.reshape(arreglo,(2,3),"A")

array([[5, 4, 3],
       [2, 8, 3]])

* Usar este último si bien es muy rápido, no es recomendable ya que perdemos un poco el control sobre lo que estamos haciendo