# Tipos de Datos

In [12]:
import numpy as np

In [15]:
arreglo = np.array([1,2,3,4], dtype="float64") #Modifio el dtype
arreglo

array([1., 2., 3., 4.])

* Dtype

In [16]:
arreglo.dtype

dtype('float64')

* Modificar el tipo de dato

In [17]:
arreglo = arreglo.astype(np.int64) #np.tipo_de_dato

In [18]:
arreglo

array([1, 2, 3, 4], dtype=int64)

* Cambio a tipo booleano

In [21]:
#Se interpreta que solo los 0 son falsos cualquier otra cosa es Verdadero.
arreglo = np.array([0,1,2,3,4]) #Modifio el dtype
arreglo = arreglo.astype(np.bool_)
arreglo

array([False,  True,  True,  True,  True])

* Cambio a String

In [27]:
arreglo = np.array([0,1,2,3,4]) #Modifio el dtype
arreglo = arreglo.astype(np.string_)
arreglo[1]

b'1'

* De String a Entero

In [29]:
arreglo = np.array(["0","1","2","3","4"])
arreglo = arreglo.astype(np.int32)

In [30]:
arreglo

array([0, 1, 2, 3, 4])

# Conclusión

* Los arreglos en numpy deben ser todos de un solo tipo de dato
* Si no fuese así se perdería su optimización