# Matriz Diagonal

In [2]:
import numpy as np
vector = np.array([1,2,3,4,5])
matriz = np.diag(vector)
matriz

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [4]:
#Matriz diagonal no cuadrada
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


* La Matriz Diagonal 

In [6]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [9]:
v1 = np.array([[1,1,1,1]])
print(v1)
print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [11]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
A_inv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [13]:
identidad = A.dot(A_inv)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
A_inv_cal = np.linalg.inv(A)
A_inv_cal

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

# Matriz Simétrica

* Cuando se transpone no cambia

In [18]:
#Una matriz diagonal es por defecto y naturaleza una matriz simétrica
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [19]:
simetrica = np.array([[1,2,3],[2,-1,7],[3,7,11]])
simetrica

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

In [23]:
#Es igual por lo que es simétrica.
simetrica.T

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

* Recordemos que la transpuesta de una multiplicacion de matrices es a cada transpuesta invertida, pero en este caso sería solo invertirlo, en caso de que sean simétricas

# Matriz Ortogonal

In [30]:
matriz = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
print(matriz[:,0].dot(matriz[:,1]))
print(matriz[:,0].dot(matriz[:,2]))
print(matriz[:,1].dot(matriz[:,2]))

0
0
0


In [36]:
#Las normas de cada fila son igual a 1. 
np.linalg.norm(matriz[:,0])
np.linalg.norm(matriz[:,1])
np.linalg.norm(matriz[:,2])

1.0

In [37]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[1,:]))

0
0
0


In [38]:
np.linalg.norm(matriz[0,:])
np.linalg.norm(matriz[1,:])
np.linalg.norm(matriz[2,:])

1.0

* Se cumple que es una matriz ortogonal conformada por vectores ortonormales

* Se cumple que producto de transpuestas es conmutativa y te arroja la matriz identidad
* Además la transpuesta es igual a la matriz inversa, esto solo en matriz ortogonal.

In [ ]:
v = [7,-7,3], u=[1,1,0] y w=[0,0,1

In [39]:
A = np.array([[np.cos(100),-np.sin(100)],[np.sin(100),np.cos(100)]])

In [41]:
A

array([[ 0.86231887,  0.50636564],
       [-0.50636564,  0.86231887]])

In [69]:
np.linalg.norm(np.array([7,-7,3]))

10.344080432788601

In [47]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [51]:
np.linalg.inv(A) == A.T

array([[ True,  True],
       [ True,  True]])

In [61]:
print(A.dot(A.T))

[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [59]:
eps= 1e-17
A[np.abs(A) < eps] = 0

In [58]:
print(A.T.dot(A))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]


In [62]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

* Cuidado no expandas tus errores, ten encuenta que 0 a veces no lo es en python y lo toman como un número muy pequeño

In [64]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9,10, 11,12]] ).T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [73]:
A = np.array([7,-7,3])
B = np.array([1,1,0])
C = np.array([0,0,1])

In [84]:
A = np.array( [[1 3] [5 6]])
B = np.array([2,3])
A.dot(B).shape

(3,)

In [88]:
A = np.array( [[1,3],[5,6]]) + 3
A

array([[4, 6],
       [8, 9]])