# Producto Interno o Escalar

* Matriz x Vector

In [3]:
import numpy as np
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

* Multiplicar una matriz por un vector, nos devuelve otro vector

In [9]:
print(matriz)
print("---------")
print(vector)

[[1 2]
 [3 4]
 [5 6]]
---------
[2 3]


* Aquí solo se multiplica cada fila.

In [5]:
A = matriz * vector
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

* ¿Qué está pasando aquí?

In [11]:
B = matriz.dot(vector)
B

array([ 8, 18, 28])

# Producto Interno Matrices

In [12]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [13]:
A.shape

(4, 3)

In [14]:
B.shape

(3, 2)

In [18]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
B

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [17]:
#Esto funciona ya que el numero de columnas de A, es congruente con el número de filas de B
np.dot(A,B)

array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])