# Ejercicios Numpy

In [1]:
import numpy as np
#Comprobamos la version de nuestro numpy as np
print(np.__version__)


1.22.3


In [4]:
#Crear un Arreglo de una dimensión, osea un vector
arreglo = np.array([1,2,3])
print(arreglo)


[1 2 3]


In [8]:
#Crear un arreglo booleano de 3x3
#Parametros de la funcion full → (dimension) (elemento) (tipo dato elemento)
arreglo = np.full((3,3),1,dtype=bool)
print(arreglo)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
#Crear un arreglo a partir de otro teniendo como referencia una condición
arreglo = np.arange(10)
print(arreglo)
#Usaremos una mascara, esta contendrá la condición que deseamos
mascara = arreglo%2!=0
arreglo_resultado = arreglo[mascara]
print(arreglo_resultado)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [13]:
#Cambiar los elementos de un arreglo según una condición, afecta el arreglo original
arreglo = np.arange(10)
#Guardamos la condicion, que sería en teoría una mascara
condicion = arreglo%2!=0
#cambiamos los datos, el arreglo mismo se actualiza
arreglo[condicion] = -1
print(arreglo)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [20]:
#Cambiar los elementos de un arreglo según una condición, sin afectarlo como tal
arreglo = np.arange(10)
#Un nuevo arreglo sera igual a la funcion where
#Esta recibe como parametro → nuestra condicion de cambio, elemento por el cual 
#cambiamos, y finalmente el arreglo principal
arreglo_salida = np.where(arreglo%2!=0,-1,arreglo)
print(arreglo)
print(arreglo_salida)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [30]:
#Redimensionar un arreglo
#La Funcion reshape redimensiona un arreglo, podemos pasar de un vector a un 3x3
vector = np.arange(9).reshape((3,3))
print(vector)
#OJO: Para redimensionar basta que sepamos un numero de filas o columnas admitibles
#Si el siguiente dato es -1 ya estaría hecho

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
#Creamos 2 Arreglos para agruparlos verticalmente
a = np.arange(10).reshape(2,-1) #Se que tendrá 2 filas, por lo que 5 columnas (-1)
b = np.arange(10).reshape(2,-1)
c = np.arange(10).reshape(2,-1)
#Primera forma de unir verticalmente 2 arrys, axis = 0 significa verticalmente
arreglo = np.concatenate((a,b,c), axis=0)
print(arreglo) #Doble parentesis

#Segunda forma de unir verticalmente 2 array, en este caso debemos insertarlo como
#una lista, sin ningun parametro adicional usando el vstack. 
arreglo = np.vstack([a,b,c])
print(arreglo) #Un parentesis, una lista

#Tercera Forma de unir verticalmente 2 array, usamos np.r_ junto a nuestra lista de arreglos
arreglo = np.r_[a,b,c]
print(arreglo) #Solo lista

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [248]:
#Entiende ROW es
#Creamos 2 Arreglos para agruparlo horizontalmente
a = np.arange(10).reshape(2,-1) 
b = np.arange(10).reshape(2,-1)
c = np.arange(10).reshape(2,-1)

arreglo = np.concatenate((a,b,c), axis=1)
print(arreglo) 

arreglo = np.hstack([a,b,c])
print(arreglo) 


arreglo = np.c_[a,b,c]
print(arreglo) 

[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9 5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9 5 6 7 8 9]]
[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9 5 6 7 8 9]]


In [56]:
#Crear secuencias especiales a partir de tu arreglo
arreglo = np.arange(1,4)
print(arreglo)
#Con repeat, creamos un arreglo cuyos elementos se repiten n veces del arreglo base
a1 = arreglo.repeat(3)
print(a1)
#Con tile, hacemos un arreglo, que se conforme de nuestro arreglo base repetido n veces
a2 = np.tile(arreglo,3)
print(a2)

arreglo_resultado = np.concatenate((a1,a2),axis = 0)
print(arreglo_resultado)

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [60]:
#Operaciones de Conjuntos pero en Arreglos
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Operacion Interseccion
print(np.intersect1d(a,b))
#Operacion Union
print(np.union1d(a,b))
#Operacion Resta de Conjuntos
print(np.setdiff1d(a,b))
#Operacion Diferencia Simétrica
print(np.setxor1d(a,b))

[2 4]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 6]
[ 1  3  5  6  7  8  9 10]


In [63]:
#Crear un arreglo a partir de otro pero eliminar todos los que compartan con otro arreglo

a = np.array([1,2,5,7,8,9])
b = np.array([1,8])
d = np.array([2,7])

c = np.setdiff1d(np.setdiff1d(a,b),d)

print(c)

[5 9]


In [80]:
#En que indices estos arreglos están repetidos
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#DONDE A es IGUAL a B?
arreglo_indices = np.where(a==b)
print(type(arreglo_indices)) #Arroja al parecer una tupla
print((arreglo_indices)) 
#Así podemos obtener los elementos repetidos

#Ojo un arreglo puede recibir una lista para recorrerse o un arreglo, estos seran los indices, solo que si estan en orden se recorren pues en orden




<class 'tuple'>
(array([1, 3, 5, 7], dtype=int64),)


In [85]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
#Cuando manejamos dos o más condiciones para extraer un dato en un arreglo
#Debemos colocarlos en paréntesis y relacionarlos con & lo mismo con |
condicion = (a>=5) & (a<=10)
a = a[condicion]
print(a)

[ 6  9 10]


In [95]:
#Vectorizar una funcion, hacer que una funcion de escalar funcione en vectores


def min(x,y):
    if x<=y:
        return x
    else:
        return y

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


#Atención en el vectorize, el tipo de dato debe ir entre []
nueva_funcion = np.vectorize(min,otypes=[int])

nueva_funcion(a,b)


array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [115]:
#Intercambio o modificación de Columnas en un mismo arreglo
arreglo = np.arange(9).reshape((3,3))
print(arreglo,"\n")
#Con esto cambiamos en si el orden de las columnas
print(arreglo[:,[1,0,2]],"\n")
#Con esto cambios en si el orden las filas
print(arreglo[[0,2,1],:])
#De la misma forma podemos obtener los elementos queq queramos con este metodo.

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1 0 2]
 [4 3 5]
 [7 6 8]] 

[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [123]:
#Como invertir un arreglo 2D?, por filas? , la ultima fila será la primera
arreglo = np.arange(20).reshape((4,-1))
print(arreglo,"\n")
arreglo_inverso = arreglo[::-1]
print(arreglo_inverso)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [127]:
#Como invertir un arreglo 2D? Por columnas?, la última columna será la primera
arreglo = np.arange(20).reshape((4,-1))
print(arreglo,"\n")
arreglo_inverso = arreglo[:,::-1]
print(arreglo_inverso)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


In [146]:
#Arreglo de numeros aleatorios de 0 a 1 [n elementos] y redimensionados
arreglo = np.random.random(9).reshape((3,-1))
print(arreglo,"\n")

#Segunda Forma, directamente sin redimensionar
arreglo = np.random.random((3,3,5))
print(arreglo)


[[0.76182995 0.61597746 0.94994257]
 [0.98759514 0.99766099 0.44431734]
 [0.51386445 0.38491039 0.12801327]] 

[[[0.41129747 0.31408298 0.56278013 0.60694471 0.006047  ]
  [0.00844139 0.16164965 0.85996452 0.40875576 0.79215775]
  [0.63805243 0.26400069 0.63454378 0.94498483 0.33411003]]

 [[0.57197507 0.28136096 0.63233448 0.96550888 0.5994503 ]
  [0.55170942 0.51312328 0.44065912 0.97236298 0.78817595]
  [0.77771274 0.55875253 0.72039979 0.70678789 0.2043364 ]]

 [[0.01599844 0.01233179 0.48426646 0.51043329 0.02622115]
  [0.47157677 0.81042472 0.47401673 0.00717549 0.72910707]
  [0.1365828  0.55140881 0.56057276 0.40851079 0.74844488]]]


In [180]:
#Arreglo de números aleatorios de entre 5 a 10, y redimensionados
#En este caso usariamos random.uniform
#Recibe de parametros 2 numeros, lim inferior y lim superior, también su dimension en size = (tupla)
arreglo_random = np.random.uniform(5,10, size=(10,5))
print(arreglo_random)

[[7.8728744 9.1154965 9.3333527 5.8952653 5.5243276]
 [9.1918464 5.2256526 6.8740163 8.0320298 5.1279702]
 [6.6862568 7.0157363 7.9403806 6.0235911 7.8380123]
 [6.5183565 5.0522002 9.6726564 8.6884444 9.983075 ]
 [5.0213718 8.206595  9.2665543 7.8300833 5.0358144]
 [9.5528358 5.3427928 6.2372136 5.0496513 5.3826454]
 [6.5730984 6.686232  8.7446226 8.4435381 9.9985584]
 [9.741328  5.7328636 5.7206122 9.6984649 9.1582605]
 [6.2994226 8.6364905 5.1065562 8.7162241 6.9947789]
 [6.2225284 6.7902486 5.1586799 5.149963  7.4504362]]


In [179]:
arreglo = np.random.random((5,3))
#Con esto seteo la precission de los decimales que necesito
np.set_printoptions(precision=7)
arreglo

array([[0.1284183, 0.1058688, 0.1218222],
       [0.9836833, 0.6365011, 0.9667018],
       [0.523484 , 0.9113856, 0.2730745],
       [0.2090734, 0.9013324, 0.1343404],
       [0.4431772, 0.0045443, 0.1209077]])

In [217]:
#Para resetar las opciones de impresion hacemos lo siguiente
np.set_printoptions(suppress=False)
#Con esto establecemos una semilla para la generacion de datos aleatorios,
#de manera que colocamos una con la que podremos operar a continuacion
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3 #Estamos dividiendo entre 1000
print(rand_arr,"\n")
#Ahora nos desharemos del molesto 1e potencia de 10
np.set_printoptions(suppress=True,precision=6)
print(rand_arr)

[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]] 

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [228]:
#Si tenemos un array enorme, como lo limitamos por ejemplo para ver solo
#los primeros 3 elementos y los ultimos 3?
np.set_printoptions(threshold=np.inf)
arreglo = np.arange(100)
print(arreglo)

#Modificamos las opciones de impresion
np.set_printoptions(threshold=6)
print(arreglo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2 ... 97 98 99]


In [230]:
#Para que vuelva a la normalidad el metodo de la impresion array
np.set_printoptions(threshold=np.inf)
print(arreglo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [265]:
#Acceder un dato con una URL
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
names = np.array(names)
tabla_final = np.vstack([names,iris])



sepallength


In [272]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


C:\Users\User\AppData\Local\Temp\ipykernel_2484\1935397065.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')