In [4]:
import numpy as np
#Podemos convertir una lista en un arreglo, deben ser del mismo tipo de dato
lista = [2,4,5]
arreglo = np.array(lista)

print(sum(arreglo))

11


In [6]:
#Crear un arreglo de numeros consecutivos del 1 al 10
arreglo = np.arange(1,11)
print(arreglo)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
#Con los arreglos podemos operar facilmente sus elementos, de menos a mas complejo
arreglo = np.arange(1,5)
print(arreglo)
arreglo + 1

[1 2 3 4]


array([2, 3, 4, 5])

In [14]:
#Podemos sumar arreglos?
arreglo = np.arange(1,5)
arreglo2 = np.arange(2,6)
#En efecto los arreglos se suman de manera normal, pero obviamente con la misma dimension
print(arreglo + arreglo2)

[3 5 7 9]


In [18]:
#Suma de arreglos en 2D, en efecto es posible, solo hemos redimensionado y sumado
#Recuerda misma dimension
arreglo = np.arange(1,5).reshape(2,-1)
arreglo2 = np.arange(2,6).reshape(2,-1)
print(arreglo)
print(arreglo2)
print(arreglo + arreglo2)

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]
[[3 5]
 [7 9]]


In [20]:
#Podemos sumar los elementos de un arreglo con el metodo sum
arreglo = np.arange(1,5).reshape(2,-1)
print(arreglo)
arreglo.sum()

[[1 2]
 [3 4]]


10

In [23]:
#Si deseamos conocer la dimension de un arreglo, por supuesto usaremos shape
arreglo = np.arange(1,5).reshape(2,-1)
print(arreglo)
arreglo.shape

[[1 2]
 [3 4]]


(2, 2)

In [30]:
#Como crear un arreglo con lista de listas
lista_1 = [1,2,3]
lista_2 = [2,3,4]
lista_3 = [5,6,7]
#Donde cada lista sera la fila, delimitando las columnas por coma
arreglo = np.array([lista_1,lista_2,lista_3])
arreglo.shape


(3, 3)

In [43]:
#Encuentra las diferencias
arreglo = np.array([1,2,3])
arreglo2 = np.array([[1,2,3]])

print(arreglo) #En este tenemos meramente un vector con 3 elementos
print(arreglo2) #Este es una matriz en sí 1 x 3

#Por ejemplo podemos notar este cambio cuando transponemos, en arreglo 1 no sucece nada.
#Mientras que el arreglo2 tiene el cambio esperado. 

arreglo2.T

[1 2 3]
[[1 2 3]]


array([[1],
       [2],
       [3]])

In [46]:
#Otra forma de lograr la transposicion manualmente es:
arreglo = np.array([[1],[2],[3],[4]])
print(arreglo)

[[1]
 [2]
 [3]
 [4]]


In [51]:
#Podemos Multiplicar los elementos de nuestras matrices?
arreglo = np.arange(9).reshape(3,-1)
arreglo2 = np.arange(9).reshape(3,-1)
print(arreglo)
print(arreglo2)

producto = arreglo * arreglo2
#En efecto es posible multiplicar los elelemtnos de nuestras matrices, siempre y cuando tengan la misma dimension
print(producto)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [60]:
#Como podemos tener un arreglo con una cantidad elementos de un intervalo y que sean equidistantes.

#Con linspace lo obtenemos, fijamos un intervalo, y si deseamos le otorgamos un tipo de dato según convenga, y así creamos un arreglo (vector)
arreglo = np.linspace(0,1000,100,dtype=int)
print(arreglo)

[   0   10   20   30   40   50   60   70   80   90  101  111  121  131
  141  151  161  171  181  191  202  212  222  232  242  252  262  272
  282  292  303  313  323  333  343  353  363  373  383  393  404  414
  424  434  444  454  464  474  484  494  505  515  525  535  545  555
  565  575  585  595  606  616  626  636  646  656  666  676  686  696
  707  717  727  737  747  757  767  777  787  797  808  818  828  838
  848  858  868  878  888  898  909  919  929  939  949  959  969  979
  989 1000]


In [71]:
#Obtener un arreglo con una condicion sobre los elementos de otro
arreglo = np.arange(10,101)
condicion = arreglo%3 == 0
arreglo_resultado = arreglo[condicion]
print(arreglo_resultado)

#Ahora como seleccionamos esos datos de alguna forma?
arreglo_seleccion = np.ma.array(arreglo,mask=arreglo%3)
print(arreglo_seleccion)

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]
[-- -- 12 -- -- 15 -- -- 18 -- -- 21 -- -- 24 -- -- 27 -- -- 30 -- -- 33
 -- -- 36 -- -- 39 -- -- 42 -- -- 45 -- -- 48 -- -- 51 -- -- 54 -- -- 57
 -- -- 60 -- -- 63 -- -- 66 -- -- 69 -- -- 72 -- -- 75 -- -- 78 -- -- 81
 -- -- 84 -- -- 87 -- -- 90 -- -- 93 -- -- 96 -- -- 99 --]


In [81]:
arreglo = np.zeros((5,10))
print(arreglo)

arreglo[1,:]  = 1
arreglo[3,:] = 1
print(arreglo)

arreglo[:,2] = 2
arreglo[:,7] = 2
print(arreglo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


In [84]:
#Creamos un arreglo de 3 dimensiones, 4x2x3m cada elemento es un numero "aleatorio"
#Este aleatorio será del 0 al 1, por lo que podemos modificar su valor, ya que podemos operar con arreglos de forma facil
a = np.random.random((4,2,3)) * 1000 /2
a

array([[[165.64758145, 354.84081966, 278.32556172],
        [167.30978856, 122.5280908 , 160.32667803]],

       [[ 19.00248076, 365.8332158 , 373.25796555],
        [381.28752534, 451.86114705, 352.69231784]],

       [[166.98383117, 183.8921921 , 445.12205132],
        [246.89605699,  71.6999395 ,   5.14723893]],

       [[264.14565528, 359.06970354, 166.0081943 ],
        [ 74.17267179, 398.42994131, 198.41790692]]])

In [86]:
#Crear un arreglo random de 2 dimensiones
arreglo = np.random.random((3,4))
print(arreglo)

[[0.27883334 0.81686485 0.17508372 0.53192579]
 [0.91581694 0.93078175 0.1086264  0.29574325]
 [0.0345505  0.18275152 0.19256897 0.80866128]]


In [100]:
#Modificamos el tipo de dato de un arreglo
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=str)
#Hemos creado un arreglo, empleando una lista de listas, si bien recibimos valores enteros
#Con dtype = str hemos podido cambiar el dato a String, . 
print(a)

[['10' '200' '30' '45' '5' '50']
 ['5' '20' '30' '40' '50' '0']
 ['5' '20' '30' '40' '50' '0']
 ['5' '20' '30' '40' '50' '0']]


In [107]:
#DUDA SOBRE EL NP.INT16 O EL NP.INT8
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]],dtype=np.int16)
#Podemos sumar sus elementos
a.sum()

775

In [95]:
#Funcion desviacion estandar de los datos

39.15724620750999

In [111]:
#Poner atención sobre el axis
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]],dtype=np.int16)
print(a,"\n")
a.sort(axis=1)
print(a)

[[ 10 200  30  45   5  50]
 [  5  20  30  40  50   0]
 [  5  20  30  40  50   0]
 [  5  20  30  40  50   0]] 

[[  5  10  30  45  50 200]
 [  0   5  20  30  40  50]
 [  0   5  20  30  40  50]
 [  0   5  20  30  40  50]]


In [ ]:
#En todo caso esto a[1:3,0:3] te genera una matriz mas pequeña, quiere decir:
#Tomamos desde la fila 2 hasta la fila 3, y en las columnas desde la primera, a la tercera.
#recuerda que tienes que ver bien los numeritos

In [113]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [116]:
#Para concluir por ahora, podemos decir que matrix, es en verdad una matriz
#Aquí si al multiplicarse no obtendriamos solo el producto de sus elementos en otro objetp

a = np.matrix('1 2; 3 4')
b = np.matrix("1 4; 0 3")
#Esto es lo que me gusta, multiplicar matrices.
c = a *b
print(c)

[[ 1 10]
 [ 3 24]]
