In [2]:
#Ejercicio 1:
import numpy as np
import numpy.random as ran
#Version Importante para verificar
print(np.__version__)

1.22.3


In [5]:
#Ejercicio2
arreglo = np.arange(10)
print(arreglo)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
#Ejercicio3 - full es llenar un arreglo entero de un elemento
arreglo = np.full(shape=(3,3),fill_value=1,dtype=bool)
print(arreglo)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
#Ejercicio 4 - crear un arreglo con una condicion
arreglo = np.arange(10)
print(arreglo)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
#Crear un Arreglo bajo una condicion desde otro, crea un mask cuando la condicion
#sea mas grane
arreglo = np.arange(10)
print(arreglo)
print(arreglo[arreglo%2!=0])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [21]:
#Ejercicio 5 - Usar un enmascaramiento para cambiar un dato especifico
arreglo = np.arange(10)
arreglo[arreglo%2!=0] = -1
print(arreglo)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [24]:
#Redimensionar un arreglo
arreglo = np.arange(0,9).reshape((3,3))
print(arreglo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#Los indices que no son 0
arreglo = np.array([1,2,3,4,0,0])
indices = arreglo.nonzero()
print(indices)

(array([0, 1, 2, 3], dtype=int64),)


In [39]:
#Randint "numeros random enteros", obtener numeros maximo y minimos de un arreglo
arreglo = np.random.random((10,10))
print(np.max(arreglo))
print(np.min(arreglo))

0.9993456808987893
0.011311073144473105


In [47]:
#Mediana
arreglo = np.random.random (30)
print(np.median(arreglo))

0.5728281593490226


In [55]:
arreglo = np.zeros((6,6))
print(arreglo)
arreglo[0,:] = 1
arreglo[-1,:] = 1
arreglo[:,0] = 1
arreglo[:,-1] = 1
print(arreglo)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [60]:
#Rellenas de 1 
Z = np.ones((10,10))
#Desde la fila 1 hasta la penultima, Desde la columna 1 hasta la penultima
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [80]:
#Crear un margen de un array
Z = np.arange(25).reshape((5,5))
#Recibe el arreglo, el margen, el valor
Z = np.pad(Z, pad_width=3, constant_values=78)
print(Z)


[[78 78 78 78 78 78 78 78 78 78 78]
 [78 78 78 78 78 78 78 78 78 78 78]
 [78 78 78 78 78 78 78 78 78 78 78]
 [78 78 78  0  1  2  3  4 78 78 78]
 [78 78 78  5  6  7  8  9 78 78 78]
 [78 78 78 10 11 12 13 14 78 78 78]
 [78 78 78 15 16 17 18 19 78 78 78]
 [78 78 78 20 21 22 23 24 78 78 78]
 [78 78 78 78 78 78 78 78 78 78 78]
 [78 78 78 78 78 78 78 78 78 78 78]
 [78 78 78 78 78 78 78 78 78 78 78]]


In [81]:
0*np.nan

nan

In [84]:
np.nan == np.nan

False

In [ ]:
help(np.nan)

In [90]:
my = {1234,3}
np.nan in my

False

In [95]:
0.3 == 3.0*0.1

False

In [ ]:
#Procurar no multiplizar un flotante con un numero y compararlo con su contraparte.

In [ ]:
#Indeterminación es igual a
np.nan
#Infinito
np.inf

In [ ]:
#Ejercicios: Existe una funcion para rellenar la diagonal.


In [98]:
#Redimensionar
arreglo = np.arange(9).reshape((3,3))
print(arreglo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [112]:
#Ejercicio 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
#Juntar una matriz vertical 
print(np.vstack([a, b]))
#Juntar una matriz horizontal
print(np.hstack([a,b]))
#Forma Alternativa con Concatenate, el axis indica de que modo lo junta
print(np.concatenate([a,b],axis=0))
#Forma Alternativa alternativa
print(np.r_[a,b])


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [119]:
#Ejercicio 10
a = np.array([1,2,3])
print(a)
#np.r_ sirve para concatenar
#np.repeat regresa un vector con el numero de elementos repetido n veces
#np.tile nos devuelve un vector, con dicho arreglo repetido una n cantidad de veces
np.r_[np.repeat(a,3),np.tile(a,3)]

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [125]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Interseccion de arreglos
np.intersect1d(a,b)
#Union de arreglos
np.union1d(a,b)
#Diferencia de arreglos (Como Conjunto)
np.setdiff1d(a,b)
#Diferencia Simetrica
np.setxor1d(a,b)


array([ 1,  3,  5,  6,  7,  8,  9, 10])

In [127]:
#En que indices de estos arreglos tienen el mismo elemento?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Te arroja DONDE se cumple esa condicion
np.where(a==b)

(array([0, 2, 4, 6, 8, 9], dtype=int64),)

In [143]:
#Extraer un arreglo con una condicion mas compleja

#En una mascara o condiciones multiples enfocados en un arreglo el operador and no funciona sino &
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5) & (a<=10) & (a!=9))
a[index]


array([ 6, 10])

In [151]:
#Funcion de maximo + involucrar vectores
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

#Esta variable se convierte en una funcion, con las caracteristicas de maxx
#Funcion vectorizada
#Vectorizas de la funcion, y le dices el tipo dato que devuelve
pair_max = np.vectorize(maxx,otypes=[int])

#Ahora pair_max es una funcion
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])