In [2]:
import numpy as np

In [3]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [4]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

# Broadcasting

In [5]:
# No se puede sumar en condiciones normales
matriz.T + vector

array([[ 4,  7, 10],
       [ 5,  8, 11]])

# Ejemplificación

In [6]:
#Observa este caso
matriz + 23

array([[24, 25],
       [26, 27],
       [28, 29]])

* Internamente python está realizando broadcasting

* Se le llama broadcasting, extender el elemento de menor dimensión hasta completar o igualar el de mayor dimensión