# Matrices Elementales

In [1]:
import numpy as np

* Matriz identidad

In [2]:
identidad = np.eye(4)

* Todos los elementos se definen como float, de manera que la diagonal se encuentra siempre compuesto de la unidad

In [3]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
vector = np.array([2,3,4,5])

* Es el elemento neutro, de las operaciones con matrices

In [5]:
vector.dot(identidad)

array([2., 3., 4., 5.])

# Transformación Lineal

* Calculo de la Inversa de una Matriz

In [7]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [8]:
#Nos otorga la inversa de la matriz. 
inversa_A = np.linalg.inv(A)

* El producto de una matriz con su inversa siempre es la identidad

In [9]:
#Comprobado
A.dot(inversa_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* Si la determinante es 0 no tiene inversa y si es así se le llama matriz singular, o si tambien hablamos de una matriz no cuadrada

In [13]:
np.linalg.det(A)

1.0