In [2]:
import numpy as np
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
    ],[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]]
    ]])

In [3]:
vector.T

array([1, 2, 3])

* Transponer es cambiar la fila a que sea columna

In [4]:
matriz.T

array([[1, 3],
       [2, 4]])

In [6]:
tensor

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]]])

* Propiedad: Tranpuesta de tranpuesta es = Matriz original

In [8]:
tensor.T

array([[[[ 1,  1],
         [11, 11],
         [21, 21]],

        [[ 4,  4],
         [14, 14],
         [24, 24]],

        [[ 7,  7],
         [17, 17],
         [27, 27]]],


       [[[ 2,  2],
         [12, 12],
         [22, 22]],

        [[ 5,  5],
         [15, 15],
         [25, 25]],

        [[ 8,  8],
         [18, 18],
         [28, 28]]],


       [[[ 3,  3],
         [13, 13],
         [23, 23]],

        [[ 6,  6],
         [16, 16],
         [26, 26]],

        [[ 9,  9],
         [19, 19],
         [29, 29]]]])

# Suma de Matriz

* Las Matrices deben de poseer la misma dimensión

In [11]:
matriz_a = matriz
matriz_b = matriz * 2

In [12]:
matriz_a + matriz_b

array([[ 3,  6],
       [ 9, 12]])

* Si sumas una matriz a un escalar te devuelve una matriz con cada elemento aumentado en dicho escalar

In [15]:
matriz_a 

array([[1, 2],
       [3, 4]])

In [18]:
matriz = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
matriz + matriz.T

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])